#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import ora from 'ora';
import yaml from 'js-yaml';
import { askUser } from './prompt.js';
import { generateTypes, normalizeSchema } from './generator.js';
import { extractPathEnum, extractHttpMethodEnum, extractPayloads, type OpenApiSchema } from './paths.js';

async function readSchema(source: string): Promise<{ raw: string; contentType: string }> {
  if (source.startsWith('http://') || source.startsWith('https://')) {
    const response = await fetch(source);
    if (!response.ok) {
      throw new Error(`Failed to fetch schema: ${response.status} ${response.statusText}`);
    }
    const contentType = response.headers.get('content-type') ?? '';
    const raw = await response.text();
    return { raw, contentType };
  }

  const resolved = path.resolve(source);
  if (!fs.existsSync(resolved)) {
    throw new Error(`File not found: ${resolved}`);
  }
  const raw = fs.readFileSync(resolved, 'utf-8');
  const ext = path.extname(resolved).toLowerCase();
  const contentType = ext === '.yaml' || ext === '.yml' ? 'application/yaml' : 'application/json';
  return { raw, contentType };
}

function parseSchema(raw: string, contentType: string): unknown {
  const isYaml =
    contentType.includes('yaml') ||
    contentType.includes('text/plain');

  if (isYaml) {
    return yaml.load(raw);
  }

  // Try JSON first, fall back to YAML (some servers return YAML with wrong content-type)
  try {
    return JSON.parse(raw);
  } catch {
    return yaml.load(raw);
  }
}

async function main() {
  console.log('\nopenapi-ts-gen — OpenAPI → TypeScript generator\n');

  const { source, outputDir } = await askUser();

  const schemaPath = path.join(outputDir, 'schema.ts');
  const apiPath = path.join(outputDir, 'api.ts');

  const spinner = ora('Reading schema…').start();

  let raw: string;
  let contentType: string;
  try {
    ({ raw, contentType } = await readSchema(source));
    spinner.succeed('Schema loaded');
  } catch (err) {
    spinner.fail(`Failed to read schema: ${(err as Error).message}`);
    process.exit(1);
  }

  spinner.start('Generating TypeScript types…');
  let typeStr: string;
  let schema: OpenApiSchema;
  try {
    const parsed = parseSchema(raw, contentType) as Record<string, unknown>;
    const normalized = await normalizeSchema(parsed);
    typeStr = await generateTypes(normalized);
    schema = normalized as OpenApiSchema;
    spinner.succeed('TypeScript types generated');
  } catch (err) {
    spinner.fail(`Type generation failed: ${(err as Error).message}`);
    process.exit(1);
  }

  spinner.start('Extracting route enums & payload types…');
  let enumStr: string;
  let methodStr: string;
  let payloadStr: string;
  try {
    enumStr = extractPathEnum(schema);
    methodStr = extractHttpMethodEnum(schema);
    payloadStr = extractPayloads(schema);
    spinner.succeed('Route enums & payload types extracted');
  } catch (err) {
    spinner.fail(`Extraction failed: ${(err as Error).message}`);
    process.exit(1);
  }

  // schema.ts — raw OpenAPI types only
  const schemaOutput = [
    '// ── Generated by openapi-ts-gen ─────────────────────────────────────────────',
    '// Do not edit manually. Re-run openapi-ts-gen to regenerate.',
    '',
    typeStr.trim(),
    '',
  ].join('\n');

  // api.ts — ApiRoute enum + payload types, imports paths from schema.ts
  const apiSections = [
    '// ── Generated by openapi-ts-gen ─────────────────────────────────────────────',
    '// Do not edit manually. Re-run openapi-ts-gen to regenerate.',
    "import type { paths } from './schema';",
    '',
  ];
  if (enumStr) apiSections.push(enumStr, '');
  if (methodStr) apiSections.push(methodStr, '');
  if (payloadStr) apiSections.push(payloadStr, '');

  const apiOutput = apiSections.join('\n');

  try {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    fs.writeFileSync(schemaPath, schemaOutput, 'utf-8');
    fs.writeFileSync(apiPath, apiOutput, 'utf-8');
  } catch (err) {
    console.error(`\nFailed to write output files: ${(err as Error).message}`);
    process.exit(1);
  }

  console.log(`\n✓ Schema types      → ${schemaPath}`);
  console.log(`✓ Routes & payloads → ${apiPath}`);
}

main().catch((err) => {
  console.error('\nUnexpected error:', err);
  process.exit(1);
});
