#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import ora from 'ora';
import { askUser } from './prompt.js';
import { generateTypes } from './generator.js';
import { extractPathEnum, extractPayloads } from './paths.js';

async function readSchema(source: string): Promise<string> {
  if (source.startsWith('http://') || source.startsWith('https://')) {
    const response = await fetch(source);
    if (!response.ok) {
      throw new Error(`Failed to fetch schema: ${response.status} ${response.statusText}`);
    }
    return response.text();
  }

  const resolved = path.resolve(source);
  if (!fs.existsSync(resolved)) {
    throw new Error(`File not found: ${resolved}`);
  }
  return fs.readFileSync(resolved, 'utf-8');
}

async function main() {
  console.log('\nopenapi-ts-gen — OpenAPI → TypeScript generator\n');

  const { source, outputDir } = await askUser();

  const schemaPath = path.join(outputDir, 'schema.ts');
  const apiPath = path.join(outputDir, 'api.ts');

  const spinner = ora('Reading schema…').start();

  let rawJson: string;
  try {
    rawJson = await readSchema(source);
    spinner.succeed('Schema loaded');
  } catch (err) {
    spinner.fail(`Failed to read schema: ${(err as Error).message}`);
    process.exit(1);
  }

  spinner.start('Generating TypeScript types…');
  let typeStr: string;
  try {
    typeStr = await generateTypes(source);
    spinner.succeed('TypeScript types generated');
  } catch (err) {
    spinner.fail(`Type generation failed: ${(err as Error).message}`);
    process.exit(1);
  }

  spinner.start('Extracting route enums & payload types…');
  let enumStr: string;
  let payloadStr: string;
  try {
    const schema = JSON.parse(rawJson);
    enumStr = extractPathEnum(schema);
    payloadStr = extractPayloads(schema);
    spinner.succeed('Route enums & payload types extracted');
  } catch (err) {
    spinner.fail(`Extraction failed: ${(err as Error).message}`);
    process.exit(1);
  }

  // schema.ts — raw OpenAPI types only
  const schemaOutput = [
    '// ── Generated by openapi-ts-gen ─────────────────────────────────────────────',
    '// Do not edit manually. Re-run openapi-ts-gen to regenerate.',
    '',
    typeStr.trim(),
    '',
  ].join('\n');

  // api.ts — ApiRoute enum + payload types, imports paths from schema.ts
  const apiSections = [
    '// ── Generated by openapi-ts-gen ─────────────────────────────────────────────',
    '// Do not edit manually. Re-run openapi-ts-gen to regenerate.',
    "import type { paths } from './schema';",
    '',
  ];
  if (enumStr) apiSections.push(enumStr, '');
  if (payloadStr) apiSections.push(payloadStr, '');

  const apiOutput = apiSections.join('\n');

  try {
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    fs.writeFileSync(schemaPath, schemaOutput, 'utf-8');
    fs.writeFileSync(apiPath, apiOutput, 'utf-8');
  } catch (err) {
    console.error(`\nFailed to write output files: ${(err as Error).message}`);
    process.exit(1);
  }

  console.log(`\n✓ Schema types      → ${schemaPath}`);
  console.log(`✓ Routes & payloads → ${apiPath}`);
}

main().catch((err) => {
  console.error('\nUnexpected error:', err);
  process.exit(1);
});
